apiVersion: v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: web
spec:
  containers:
    - name: web-app
      image: app
      ports:
        - containerPort: 9000
  replicas: 2
  selector:
    matchLabels:
      type: web